
[General]
	#Frequency of That Thing spawning
	"Spawn Chance" = 0.4
	#Chance for structures to generate
	"Structure generation frequency" = 0.5
	#should That Thing change Do Mob Spawning gamerule
	"Change gamerule" = true
	#amount of ticks That Thing will chase you
	"chase time" = 800.0
	#Amount of ticks that thing will leave you alone
	"leave time" = 72000.0
	#message that apears after beating that thing telling for how long it will leave
	"leave message" = "That Thing has left for 3 days..."

