
[system_time]
	#Synchronize game world time with system time
	sync_to_system_time = false
	#Sync time every n ticks
	#Range: 1 ~ 864000
	sync_to_system_time_rate = 20

[arbitrary_time]
	#How long daytime lasts (0 - 12000)
	#Range: 1 ~ 178956
	day_length_minutes = 20
	#How long nighttime lasts (12000 - 24000)
	#Range: 1 ~ 178956
	night_length_minutes = 10

[miscellaneous]
	debugMode = false

